### PR TITLE
scripts: allow setting a default configuration with --conf

### PR DESCRIPTION
**Pull request by doudou**
The syntax is --conf=,section0,section1 (i.e. omit the task name)

### CODE REVIEW

**Comment by jakobs** [comment]
Ok, the idea behind it is to separate functionality, which is only relevant for scripts?

**Comment by doudou** [comment]
It is more to provide functionality to write scripts. This functionality does not exist anywhere else.

Having thought more about it, I start to believe it should be moved to the rock bundle setup and we should promote bundles more. This adds yet-another-interface (Orocos::Scripts.run instead of Orocos.run, ...) which adds to even more confusion.

**Comment by doudou** [comment]
@jakobs, @goldhoorn: given that the code is there, I'd like to merge this (regardless of whether it should be discontinued in favor of code in the bundles or wherever).

**Comment by goldhoorn** [comment]
ack

On 20.02.2015 15:12, Sylvain Joyeux wrote:
>
> @jakobs <https://github.com/jakobs>, @goldhoorn 
> <https://github.com/goldhoorn>: given that the code is there, I'd like 
> to merge this (regardless of whether it should be discontinued in 
> favor of code in the bundles or wherever).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/pull/30#issuecomment-75243319>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
done

**Pull request merged**
