### PR TITLE
Fix running the test suite

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by goldhoorn** [comment]
If i call rake test i still get a error:
```
/home/goldhoorn/install/bin/ruby  -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/suite.rb"' -- 
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /home/goldhoorn/install/lib/ruby/1.9.1/minitest/autorun.rb:14:in `<top (required)>'
  -e:1:in `<main>'
MiniTest::Unit.autorun is now Minitest.autorun. From /home/goldhoorn/install/lib/ruby/1.9.1/minitest/autorun.rb:18:in `<top (required)>'
Cannot require 'typelib'
If you are using Rock, the 'typelib' package should have been installed automatically.
First, make sure that you have loaded autoproj's env.sh script before continuing
Second, typelib should be installed in tools/typelib from the root of your Rock installation.
If it is not the case, report this to the rock developers. To workaround, run
  amake typelib
and try again.
rake aborted!
Command failed with status (1): [/home/goldhoorn/install/bin/ruby  -Ilib:bi...]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by doudou** [comment]
I'm not running the tests with rake test ... probably the reason why. I'll check it out

**Comment by goldhoorn** [comment]
Then btw. how are you running the tests?

**Comment by goldhoorn** [comment]
btw with this patch applied i got:
```
[09:07:35 goldhoorn orocos.rb]$ ruby test/test_base.rb 
use of MQueue disabled. Set USE_MQUEUE=1 to enable
use of ROS disabled. Set USE_ROS=1 to enable
Run options: --seed 41537

# Running:

.....EEEEEE.

Finished in 1.242545s, 9.6576 runs/s, 3.2192 assertions/s.

  1) Error:
the Orocos module::#find_orocos_type_name_by_type#test_0001_can be given an opaque type directly:
OroGen::TypekitNotFound: cannot find an installed typekit called echo
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/pkg_config.rb:99:in `typekit_model_text_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/base.rb:237:in `typekit_model_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:75:in `block in load_typekit'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `synchronize'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `load_typekit'
    test/test_base.rb:10:in `block (3 levels) in <main>'


  2) Error:
the Orocos module::#find_orocos_type_name_by_type#test_0003_converts a non-exported intermediate type to the corresponding opaque:
OroGen::TypekitNotFound: cannot find an installed typekit called echo
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/pkg_config.rb:99:in `typekit_model_text_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/base.rb:237:in `typekit_model_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:75:in `block in load_typekit'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `synchronize'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `load_typekit'
    test/test_base.rb:10:in `block (3 levels) in <main>'


  3) Error:
the Orocos module::#find_orocos_type_name_by_type#test_0004_converts a non-exported m-type to the corresponding opaque-containing type:
OroGen::TypekitNotFound: cannot find an installed typekit called echo
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/pkg_config.rb:99:in `typekit_model_text_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/base.rb:237:in `typekit_model_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:75:in `block in load_typekit'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `synchronize'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `load_typekit'
    test/test_base.rb:10:in `block (3 levels) in <main>'


  4) Error:
the Orocos module::#find_orocos_type_name_by_type#test_0006_raises if given a non-exported type:
OroGen::TypekitNotFound: cannot find an installed typekit called echo
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/pkg_config.rb:99:in `typekit_model_text_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/base.rb:237:in `typekit_model_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:75:in `block in load_typekit'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `synchronize'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `load_typekit'
    test/test_base.rb:10:in `block (3 levels) in <main>'


  5) Error:
the Orocos module::#find_orocos_type_name_by_type#test_0005_successfully converts a basic type to the corresponding orocos type name:
OroGen::TypekitNotFound: cannot find an installed typekit called echo
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/pkg_config.rb:99:in `typekit_model_text_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/base.rb:237:in `typekit_model_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:75:in `block in load_typekit'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `synchronize'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `load_typekit'
    test/test_base.rb:10:in `block (3 levels) in <main>'


  6) Error:
the Orocos module::#find_orocos_type_name_by_type#test_0002_can be given an opaque-containing type directly:
OroGen::TypekitNotFound: cannot find an installed typekit called echo
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/pkg_config.rb:99:in `typekit_model_text_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orogen/lib/orogen/loaders/base.rb:237:in `typekit_model_from_name'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:75:in `block in load_typekit'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `synchronize'
    /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/typekits.rb:74:in `load_typekit'
    test/test_base.rb:10:in `block (3 levels) in <main>'

12 runs, 4 assertions, 0 failures, 6 errors, 0 skips

```

**Comment by doudou** [comment]
You need to build the test modules before you run anything. Either run

~~~
rake setup:orogen_all
~~~

or https://github.com/rock-core/package_set/pull/37 and do

~~~
autoproj test --enable=tools/orocos.rb
autoproj osdeps
amake
~~~

(The latter will do parallel builds while the former will compile in -j1)

**Comment by goldhoorn** [comment]
When calling rake test i still get the same error:
```
[11:10:29 goldhoorn orocos.rb]$ rake test
/home/goldhoorn/install/bin/ruby  -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/suite.rb"' -- 
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /home/goldhoorn/install/lib/ruby/1.9.1/minitest/autorun.rb:14:in `<top (required)>'
  -e:1:in `<main>'
MiniTest::Unit.autorun is now Minitest.autorun. From /home/goldhoorn/install/lib/ruby/1.9.1/minitest/autorun.rb:18:in `<top (required)>'
Cannot require 'typelib'
If you are using Rock, the 'typelib' package should have been installed automatically.
First, make sure that you have loaded autoproj's env.sh script before continuing
Second, typelib should be installed in tools/typelib from the root of your Rock installation.
If it is not the case, report this to the rock developers. To workaround, run
  amake typelib
and try again.
rake aborted!
Command failed with status (1): [/home/goldhoorn/install/bin/ruby  -Ilib:bi...]

Tasks: TOP => test
(See full trace by running task with --trace)
```

When running the test suite manual (full text: http://dumptext.com/pkZkSFjq)
```
...............

Finished in 304.045848s, 1.2761 runs/s, 5.2624 assertions/s.

  1) Failure:
Orocos::TaskContext#test_0011_should raise CORBA::ComError when #port is called on a dead remote process [/home/goldhoorn/bootstraps/master/tools/orocos.rb/test/test_task.rb:104]:
[Orocos::CORBA::ComError] exception expected, not
Class: <Orocos::InterfaceObjectNotFound>
Message: <"task /simple_source_source does not have a port named cycle">
---Backtrace---
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context.rb:522:in `block in port'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context.rb:516:in `port'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/test/test_task.rb:104:in `block (4 levels) in <top (required)>'
---------------


  2) Failure:
Orocos::TaskContext#test_0017_should raise CORBA::ComError when state-related operations are called on a dead process [/home/goldhoorn/bootstraps/master/tools/orocos.rb/test/test_task.rb:183]:
[Orocos::CORBA::ComError] exception expected, not
Class: <Orocos::InterfaceObjectNotFound>
Message: <"task /simple_source_source does not have a port named state">
---Backtrace---
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context.rb:522:in `block in port'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context.rb:516:in `port'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context.rb:179:in `state_reader'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context.rb:193:in `peek_state'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/lib/orocos/task_context_base.rb:730:in `state'
/home/goldhoorn/bootstraps/master/tools/orocos.rb/test/test_task.rb:183:in `block (4 levels) in <top (required)>'
---------------


  3) Failure:
Orocos::Async::CORBA::OutputPort::When connect to a remote task#test_0003_must call on_data if new data are available and a block is registered [/home/goldhoorn/bootstraps/master/tools/orocos.rb/test/async/test_ports.rb:45]:
Failed assertion, no message given.


  4) Failure:
Orocos::Async::NameService#test_0005_should report that new task are added and removed [/home/goldhoorn/bootstraps/master/tools/orocos.rb/test/async/test_name_service.rb:56]:
Expected: 1
  Actual: 2

388 runs, 1600 assertions, 4 failures, 0 errors, 0 skips
```

**Comment by doudou** [comment]
"rake test" should be fixed by installing the minitest gem manually. See https://github.com/rock-core/package_set/pull/56 first, and then we would have to add a test_depend dependency on it in the package.

As for the tests not passing, it's not part of this pull request. The PR was to make the tests "RUN" which is already a big improvement.

**Comment by goldhoorn** [comment]
I'm sorry still get the same error when calling ```rake test``` i had minitest already installted

**Comment by goldhoorn** [comment]
btw. i installed minitest simply by running ```gem install minitest``` hope this is the right one.

**Comment by doudou** [comment]
> btw. i installed minitest simply by running gem install minitest hope this is the right one.

Should be. The only thing I can say is "it works for me" :(

**Comment by goldhoorn** [comment]
Do you have a idea why typelib could not be found  i assume this is the 
core fault

ps. typelib is there and valid ([18:07:29 goldhoorn dev-avalon-21]$ ruby 
-e "puts require 'typelib'")

On 10.06.2015 17:57, Sylvain Joyeux wrote:
>
>     btw. i installed minitest simply by running gem install minitest
>     hope this is the right one.
>
> Should be. The only thing I can say is "it works for me" :(
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/pull/54#issuecomment-110810410>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
woahhh, sorry my fault i had a crappy install here (rake was leftover from a manual ruby installation outside rock)

everything is valid here...

**Comment by doudou** [comment]
No problem. It happens to the best of us ;-)

**Comment by goldhoorn** [comment]
what i'm still wondering why the rake gem was not installed by default?

If it is not needed why is not a bin for rake2.1 (similar to the 
install/bin/gem created?)



On 10.06.2015 18:31, Sylvain Joyeux wrote:
>
> No problem. It happens to the best of us ;-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/pull/54#issuecomment-110824113>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
rake should be installed with the ruby-rake ubuntu package

**Comment by goldhoorn** [comment]
Is there a reason why there is no alias like for ruby in install/bin is created?

**Comment by doudou** [comment]
because it is not shipped with the ruby package and is version-independent (the same rake version can be used on any Ruby version)

**Pull request merged**
