### PR TITLE
Misc fixes and updates

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
@2maz: updated, the test suite passes (at least, passes as well as it was passing before :()

Could you have a look ?

**Comment by 2maz** [comment]
@doudou: will try this week -- let you know asap

**Comment by doudou** [comment]
Thanks !

**Comment by doudou** [comment]
OK ... it's been 20 days and we've been using this code for the same amount of time... I merge.

**Pull request merged**
