### PR TITLE
conf: Make sure the ConfManager is not constructed twice

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
Rather, make sure that .load is not called twice by raising an exception if it is. One must call clear before calling load again.

**Comment by goldhoorn** [comment]
I don't have the time to trace more in rock right now, this starts 
already to waisting too much time....
Either apply this or open a issue.

Problem is Vizkit<->orocos.rb

On 24.08.2015 17:03, Sylvain Joyeux wrote:
>
> Rather, make sure that .load is not called twice by raising an 
> exception if it is. One must call clear before calling load again.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/pull/80#issuecomment-134236245>.
>


-- 
  --
  Matthias Goldhoorn
  Unterwasserrobotik
  
  Standort Bremen:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Phone: +49 (0)421 218-64100
  Fax:   +49 (0)421 218-64150
  E-Mail: robotik@dfki.de
  
  Weitere Informationen: http://www.dfki.de/robotik
  -----------------------------------------------------------------------
  Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
  Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
  Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
  (Vorsitzender) Dr. Walter Olthoff
  Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
  Amtsgericht Kaiserslautern, HRB 2313
  Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
  USt-Id.Nr.:    DE 148646973
  Steuernummer:  19/673/0060/3
  -----------------------------------------------------------------------

**Comment by doudou** [comment]
> Problem is Vizkit<->orocos.rb

Then your problem is probably https://github.com/rock-core/gui-vizkit/pull/44, which I hit last Thursday

**Comment by goldhoorn** [comment]
What about adding a sainity check and raise isborocos is already initialized?

**Comment by doudou** [comment]
> What about adding a sainity check and raise isborocos is already initialized?

Yes, that's what I mentioned ... feel free.

**Pull request closed without merging**
