### PR TITLE
bin: make oroshell robust to task names containing colons

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by goldhoorn** [comment]
colons should be forbitten in task names as far i rember?, expect this :+1:

**Comment by doudou** [comment]
> colons should be forbitten in task names as far i rember?,

Why ?

**Comment by goldhoorn** [comment]
Because :: are used for sub-namespaces inside orogen?

**Comment by doudou** [comment]
and ? How would that be a problem. This describes deployments, not task models.

The resulting deployment might not be generate-able by orogen, but that should (and I believe, is) be enforced by the code generation part, not the spec part.

**Comment by goldhoorn** [comment]
Okay then... Thougt it is a general rule rock folows now only a limitation

**Comment by doudou** [comment]
FYI, all the gazebo integration uses ':' as name separators (as '/' would really really break things)

**Comment by goldhoorn** [comment]
as mentioned :+1: to merge then

On 19.06.2015 14:52, Sylvain Joyeux wrote:
>
> FYI, all the gazebo integration uses ':' as name separators (as '/' 
> would really really break things)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/tools-orocosrb/pull/64#issuecomment-113505857>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Pull request merged**
